model:
  # resnet18, resnet34, resnet50, resnet101, resnet152
  model: 
    - resnet18
    - resnet50  
  K: 6     # 2, 3, 4a, 4b, 4c, 5

datasets:
  - set2
  - set3
  - BUSI
  
optimizer:
  - Adam
  - lr: 5.0e-4

# trainer flag
flag:
  min_epochs: 40
  max_epochs: 80
  num_sanity_val_steps: 0
  log_every_n_steps: 10
  terminate_on_nan: True

misc:
  continue: False
  load_from: latest
  use_annotation_from: 0


scheduler: null

branch:
  default:
    scheduler: null
    optimizer:
      - Adam
      - lr: 1.e-3
        weight_decay: 1.0e-3
  M: 
    optimizer:
      - Adam
      - lr: 5.0e-8
        weight_decay: 1.0e-3
  discriminator:
    scheduler:
      factor: 0.1
      patience: 10
      cooldown: 0

dataloader:
  training:
    batch_size: 16
    shuffle: True
  scoring:
    batch_size: 16
    
paths:
  name: resnet
  model_dir: model/resnet
  log_dir: log/resnet/{date}
  post_training: src/post_training.py
