model:      # model constructor
  model: resnet34   # resnet18, resnet34, resnet50, resnet101, resnet152
  K: 6     # 2, 3, 4a, 4b, 4c, 5
training:  # training strategy
  device: cuda:0
  continue: False
  load_from: latest
  max_epoch: 80
  use_annotation_from: 0  # epoch
optimizer:
  - Adam
  - lr: 0.0005
scheduler:
  factor: 0.8
  patience: 2
  verbose: True
  cooldown: 3
branch:
  default:
    scheduler: null
dataloader:
  annotated:
    batch_size: 11
    shuffle: True
    drop_last: True
  unannotated:
    batch_size: 11
    shuffle: True
  scoring:
    batch_size: 11
paths:
  model_dir: model/resnet34/test
  log_dir: log/resnet34/{date}
