import: ./base.yml

model:
  # resnet18, resnet34, resnet50, resnet101, resnet152
  model: resnet34
  smooth: 0.1

paths:
  name: resnet
  model_dir: model/resnet/simres
  log_dir: log/resnet/{date}
  post_training: src/post_training.py
