import: ./base.yml

model:
  # resnet18, resnet34, resnet50, resnet101, resnet152
  model: resnet18
  K: 4
  smooth: 0.

flag:
  gpus: 0

paths:
  name: resnet
  model_dir: model/resnet/simres
  log_dir: log/resnet/{date}
  post_training: src/post_training.py
