model:
  in_channel: 1
  K: 6  # 2, 3, 4a, 4b, 4c, 5
  width: 32

  # for (512, 512) image, unet level + ypath level <= 8
  ulevel: 4
  # ypath like res34: [4, 6, 3]
  # ypath like res18: [2, 2, 2]
  ylevels: [2, 2]

  # margin when calculating triplet loss
  margin: 0.3

  # use torch checkpoint to save memory on training
  memory_trade: True

# coefficients when calculating multi-task loss
coefficients:
  task:
    tm: 0.5 * x ** 4

datasets:
  - set2
  - set3
  - BUSI

# trainer flag
flag:
  gpus: [3]
  min_epochs: 40
  max_epochs: 120

misc:
  augment: 1200
  continue: False
  load_from: latest
  lr_warmup:
    interval: epoch
    times: 10

optimizer:
  - AdamW
  - lr: 4e-3

# LRReduceOnPlateau only
scheduler: null

# branch is used to control behaviors of diverse param groups.
# args here will override those in optimizer and scheduler
branch:
  M:
    scheduler:
      factor: 0.9
      patience: 4

dataloader:
  training:
    # batchsize_k is the image num per class in a batch
    batchsize_k: 10
    distrib_title: Ym
    shuffle: True

  # for evaluating, validating, testing
  validating:
    batch_size: 16

paths:
  name: ynet
  model_dir: model/toynetv1/ynet
  log_dir: log/toynetv1/{date}
  post_training: src/post_training.py
