import: ./toynetv1_gpu.yml
model:
  width: 2
  memory_trade: True

flag: 
  gpus: 0
  limit_train_batches: 1
  limit_val_batches: 1
  limit_test_batches: 1

dataloader:
  scoring:
    batch_size: 2

paths:
  model_dir: model/toynetv1/tmp
  log_dir: log/toynetv1/tmp
