model:      # model constructor
  in_channel: 1
  K: 6      # 2, 3, 4a, 4b, 4c, 5
  width: 16
  ulevel: 3
  ylevel: 2   # for (512, 512) image, unet level + ypath level <= 8
  memory_trade: True

# training strategy
training:  
  device: cuda:0
  continue: False
  load_from: latest
  max_epoch: 80
  use_annotation_from: 0

optimizer:
  - AdamW

scheduler: null

branch:
  M: 
    optimizer:
      lr: 4.e-3
      weight_decay: 1.0e-3
    scheduler: 
      factor: 0.98
      patience: 2
      cooldown: 2
  B:
    scheduler: null
  discriminator:
    scheduler:
      factor: 0.1
      patience: 10
      cooldown: 0

dataloader:
  training:
    batch_size: 10
    shuffle: True
  scoring:
    batch_size: 16
    
paths:
  model_dir: model/toynetv1/ynet
  log_dir: log/toynetv1/{date}-ynet
  post_training: src/post_training.py