model:      # model constructor
  ishape:
    - 3
    - 512
    - 512
  K: 6     # 2, 3, 4a, 4b, 4c, 5
  patch_size: 32
  fc: 16
training:  # training strategy
  device: cpu
  continue: True
  load_from: latest
  max_epoch: 80
  use_unannotation_from: 20  # epoch
optimizer:
  name: Adam
  default:
    lr: 0.0005
scheduler:
  factor: 0.2
  patience: 2
  verbose: True
  cooldown: 8
dataloader:
  annotated:
    batch_size: 11
    shuffle: True
    drop_last: True
  unannotated:
    batch_size: 11
    shuffle: True
  scoring:
    batch_size: 11
paths:
  model_dir: model/toynetv1/focal
  log_dir: log/toynetv1/{date}
