model:      # model constructor
  ishape:
    - 3
    - 512
    - 512
  K: 6     # 2, 3, 4a, 4b, 4c, 5
  patch_size: 32
  fc: 32
training:  # training strategy
  device: cuda:0
  continue: False
  load_from: latest
  max_epoch: 100
  use_annotation_from: 30  # epoch
optimizer:
  Adam:
    lr: 0.0005
dataloader:
  annotated:
    batch_size: 8
    shuffle: True
    drop_last: True
  unannotated:
    batch_size: 8
    shuffle: True
  scoring:
    batch_size: 8
    shuffle: True
paths:
  model_dir: model/toynetv1/Adam
  log_dir: log/toynetv1/Adam
