model:      # model constructor
  ishape:
    - 3
    - 512
    - 512
  K: 6     # 2, 3, 4a, 4b, 4c, 5
  patch_size: 32
  fc: 16
training:  # training strategy
  device: cuda:0
  continue: False
  load_from: latest
  max_epoch: 100
  use_annotation_from: 10  # early stop
optimizer:
  - Adam
  - lr: 5.0e-4
scheduler:
  factor: 0.2
  patience: 2
  verbose: True
  cooldown: 8
branch:
  default:
    scheduler: null
    optimizer:
      - Adam
      - weight_decay: 1.0e-3
  M: 
    optimizer:
      - Adam
      - lr: 5.0e-8
        weight_decay: 1.0e-3
dataloader:
  annotated:
    batch_size: 11
    shuffle: True
    drop_last: True
  unannotated:
    batch_size: 11
    shuffle: True
  scoring:
    batch_size: 11
    shuffle: True
paths:
  model_dir: model/toynetv1/seplr
  log_dir: log/toynetv1/{date}-seplr
