model:      # model constructor
  in_channel: 1
  K: 6      # 2, 3, 4a, 4b, 4c, 5
  width: 16
  ulevel: 3
  ylevel: 2   # for (512, 512) image, unet level + ypath level <= 8
  memory_trade: True

datasets:
  - set2
  - set3
  - BUSI
  
# trainer flag
flag:
  gpus: 1
  min_epochs: 40
  max_epochs: 80
  num_sanity_val_steps: 0

misc:  
  augment: 1200
  continue: False
  load_from: latest
  use_annotation_from: 0
  log_every_n_steps: 10

optimizer:
  - AdamW

scheduler: null

branch:
  M: 
    optimizer:
      lr: 4.e-3
      weight_decay: 1.0e-3
    scheduler: 
      factor: 0.98
      patience: 2
      cooldown: 2

dataloader:
  training:
    batch_size: 10
    shuffle: True
  validating:
    batch_size: 16
    
paths:
  name: ynet
  model_dir: model/toynetv1/ynet
  log_dir: log/toynetv1/{date}
  post_training: src/post_training.py