model:      # model constructor
  ic: 1
  K: 6     # 2, 3, 4a, 4b, 4c, 5
  fc: 16
  ylevel: 1   # for (512, 512) image, unet level + ylevel <= 8
  pi: 0.5
  memory_trade: True

# training strategy
training:  
  device: cuda:0
  continue: False
  load_from: latest
  max_epoch: 80
  use_annotation_from: 0

optimizer:
  - Adam
  - lr: 5.0e-4

scheduler:
  factor: 0.2
  patience: 2
  verbose: True
  cooldown: 8

branch:
  default:
    scheduler: null
  M: 
    optimizer:
      - Adam
      - lr: 1.e-3
        weight_decay: 1.0e-3
    scheduler: 
      factor: 0.98
      patience: 2
      cooldown: 2
      verbose: False
  B:
    scheduler: null
  discriminator:
    scheduler:
      factor: 0.1
      patience: 10
      cooldown: 0

dataloader:
  training:
    batch_size: 12
    shuffle: True
  scoring:
    batch_size: 12
    
paths:
  model_dir: model/toynetv1/ynet
  log_dir: log/toynetv1/{date}-ynet
  post_training: src/post_training.py