import: ./base.yml

model:
  in_channel: 1
  # BIRADS: 2, 3, 4a, 4b, 4c, 5
  K: 3 
  width: 16

  # for (512, 512) image, unet level + ypath level <= 8
  ulevel: 4
  # ypath like res34: [4, 6, 3]
  # ypath like res18: [2, 2, 2]
  ylevels: [6, 3]

  # use anti-alias pooling when downsampling
  antialias: True

  # padding mode like that in tf.
  padding_mode: same

  # whether to use ensemble in training. bool.
  ensemble_mode: add

  # use residual connection in CBR module
  residual: True

  # like that in resnet. use with `residual` switched on
  zero_init_residual: True

  # what norm layer to use. `batchnorm`/`groupnorm`.
  norm: batchnorm

# branch is used to control behaviors of diverse param groups.
# args here will override those in optimizer and scheduler
branch:
  B:
    optimizer: null
    scheduler: null

paths:
  name: ynet
