model:      # model constructor
  in_channel: 1
  K: 6     # 2, 3, 4a, 4b, 4c, 5
  patch_sizes: 
    - 32
    - 64
    - 128
  fc: 16
  pi: 0.5
  memory_trade: True

# training strategy
training:  
  device: cuda:0
  continue: False
  load_from: latest
  max_epoch: 100
  use_annotation_from: 15

optimizer:
  - Adam
  - lr: 5.0e-4

scheduler:
  factor: 0.2
  patience: 2
  verbose: True
  cooldown: 8

branch:
  default:
    scheduler: null
    optimizer:
      - Adam
      - lr: 1.e-3
        weight_decay: 1.0e-3
  M: 
    optimizer:
      - Adam
      - lr: 5.0e-8
        weight_decay: 1.0e-3
  discriminator:
    scheduler:
      factor: 0.1
      patience: 10
      cooldown: 0

dataloader:
  training:
    batch_size: 16
    shuffle: True
  scoring:
    batch_size: 16
    
paths:
  model_dir: model/toynetv1/seplr
  log_dir: log/toynetv1/{date}-seplr
  post_training: src/post_training.py